version: "3"
services:
  mysql:
    image: original_mysql_world
    ports:
      - "10632:3306"
    build: ./mysql/
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=****
